// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3TQ_sFPrSR49IX0Tpps_YFew7-gFJocY',
    appId: '1:166477433900:web:4f0cef4cb514d7d1415589',
    messagingSenderId: '166477433900',
    projectId: 'cartadmin-d37b0',
    authDomain: 'cartadmin-d37b0.firebaseapp.com',
    storageBucket: 'cartadmin-d37b0.appspot.com',
    measurementId: 'G-NQM2W42WP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzjnXCuWEmzeirF3-mQrMBUgfBI-FX5Xc',
    appId: '1:166477433900:android:93f8b41ad346155a415589',
    messagingSenderId: '166477433900',
    projectId: 'cartadmin-d37b0',
    storageBucket: 'cartadmin-d37b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYFu5_We2sTH9NWkf1BvHzLVwHxTTbD4',
    appId: '1:166477433900:ios:5e346b324e92f335415589',
    messagingSenderId: '166477433900',
    projectId: 'cartadmin-d37b0',
    storageBucket: 'cartadmin-d37b0.appspot.com',
    iosClientId: '166477433900-99daimgnv8t3vkdur8f5i5c74rcjueu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAYFu5_We2sTH9NWkf1BvHzLVwHxTTbD4',
    appId: '1:166477433900:ios:5e346b324e92f335415589',
    messagingSenderId: '166477433900',
    projectId: 'cartadmin-d37b0',
    storageBucket: 'cartadmin-d37b0.appspot.com',
    iosClientId: '166477433900-99daimgnv8t3vkdur8f5i5c74rcjueu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartAdmin',
  );
}
